// default package
// Generated Jun 8, 2012 6:23:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * ContactType generated by hbm2java
 */
public class ContactType implements java.io.Serializable {

	private long contactType;
	private String typeName;

	public ContactType() {
	}

	public ContactType(long contactType) {
		this.contactType = contactType;
	}

	public ContactType(long contactType, String typeName) {
		this.contactType = contactType;
		this.typeName = typeName;
	}

	public long getContactType() {
		return this.contactType;
	}

	public void setContactType(long contactType) {
		this.contactType = contactType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
