// default package
// Generated Jun 8, 2012 6:23:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * EmployeeRole generated by hbm2java
 */
public class EmployeeRole implements java.io.Serializable {

	private long employeeRole;
	private Long employeeFk;
	private Long employeeRoleTypeFk;
	private String active;

	public EmployeeRole() {
	}

	public EmployeeRole(long employeeRole) {
		this.employeeRole = employeeRole;
	}

	public EmployeeRole(long employeeRole, Long employeeFk,
			Long employeeRoleTypeFk, String active) {
		this.employeeRole = employeeRole;
		this.employeeFk = employeeFk;
		this.employeeRoleTypeFk = employeeRoleTypeFk;
		this.active = active;
	}

	public long getEmployeeRole() {
		return this.employeeRole;
	}

	public void setEmployeeRole(long employeeRole) {
		this.employeeRole = employeeRole;
	}

	public Long getEmployeeFk() {
		return this.employeeFk;
	}

	public void setEmployeeFk(Long employeeFk) {
		this.employeeFk = employeeFk;
	}

	public Long getEmployeeRoleTypeFk() {
		return this.employeeRoleTypeFk;
	}

	public void setEmployeeRoleTypeFk(Long employeeRoleTypeFk) {
		this.employeeRoleTypeFk = employeeRoleTypeFk;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

}
