// default package
// Generated Jun 8, 2012 6:23:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * EnterprisePersonRelation generated by hbm2java
 */
public class EnterprisePersonRelation implements java.io.Serializable {

	private long enterprisePersonRelation;
	private Long personFk;
	private Long enterpriseFk;
	private Long entPerRelationTypeFk;

	public EnterprisePersonRelation() {
	}

	public EnterprisePersonRelation(long enterprisePersonRelation) {
		this.enterprisePersonRelation = enterprisePersonRelation;
	}

	public EnterprisePersonRelation(long enterprisePersonRelation,
			Long personFk, Long enterpriseFk, Long entPerRelationTypeFk) {
		this.enterprisePersonRelation = enterprisePersonRelation;
		this.personFk = personFk;
		this.enterpriseFk = enterpriseFk;
		this.entPerRelationTypeFk = entPerRelationTypeFk;
	}

	public long getEnterprisePersonRelation() {
		return this.enterprisePersonRelation;
	}

	public void setEnterprisePersonRelation(long enterprisePersonRelation) {
		this.enterprisePersonRelation = enterprisePersonRelation;
	}

	public Long getPersonFk() {
		return this.personFk;
	}

	public void setPersonFk(Long personFk) {
		this.personFk = personFk;
	}

	public Long getEnterpriseFk() {
		return this.enterpriseFk;
	}

	public void setEnterpriseFk(Long enterpriseFk) {
		this.enterpriseFk = enterpriseFk;
	}

	public Long getEntPerRelationTypeFk() {
		return this.entPerRelationTypeFk;
	}

	public void setEntPerRelationTypeFk(Long entPerRelationTypeFk) {
		this.entPerRelationTypeFk = entPerRelationTypeFk;
	}

}
