// default package
// Generated Jun 8, 2012 6:23:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * EntPerRelationType generated by hbm2java
 */
public class EntPerRelationType implements java.io.Serializable {

	private long entPerRelationType;
	private String typeName;

	public EntPerRelationType() {
	}

	public EntPerRelationType(long entPerRelationType) {
		this.entPerRelationType = entPerRelationType;
	}

	public EntPerRelationType(long entPerRelationType, String typeName) {
		this.entPerRelationType = entPerRelationType;
		this.typeName = typeName;
	}

	public long getEntPerRelationType() {
		return this.entPerRelationType;
	}

	public void setEntPerRelationType(long entPerRelationType) {
		this.entPerRelationType = entPerRelationType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
