// default package
// Generated Jun 8, 2012 6:23:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * ItemActionType generated by hbm2java
 */
public class ItemActionType implements java.io.Serializable {

	private long itemActionType;
	private String typeName;

	public ItemActionType() {
	}

	public ItemActionType(long itemActionType) {
		this.itemActionType = itemActionType;
	}

	public ItemActionType(long itemActionType, String typeName) {
		this.itemActionType = itemActionType;
		this.typeName = typeName;
	}

	public long getItemActionType() {
		return this.itemActionType;
	}

	public void setItemActionType(long itemActionType) {
		this.itemActionType = itemActionType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
