package backend.model.hibernate_output;
// default package
// Generated Jun 8, 2012 6:23:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * SubjectType generated by hbm2java
 */
public class SubjectType implements java.io.Serializable {

	private long subjectType;
	private String typeName;

	public SubjectType() {
	}

	public SubjectType(long subjectType) {
		this.subjectType = subjectType;
	}

	public SubjectType(long subjectType, String typeName) {
		this.subjectType = subjectType;
		this.typeName = typeName;
	}

	public long getSubjectType() {
		return this.subjectType;
	}

	public void setSubjectType(long subjectType) {
		this.subjectType = subjectType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
