package backend.model.hibernate_reverse;
// default package
// Generated Jun 8, 2012 6:23:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private long address;
	private Long addressTypeFk;
	private Long subjectFk;
	private Long subjectTypeFk;
	private String country;
	private String county;
	private String townVillage;
	private String streetAddress;
	private String zipcode;

	public Address() {
	}

	public Address(long address) {
		this.address = address;
	}

	public Address(long address, Long addressTypeFk, Long subjectFk,
			Long subjectTypeFk, String country, String county,
			String townVillage, String streetAddress, String zipcode) {
		this.address = address;
		this.addressTypeFk = addressTypeFk;
		this.subjectFk = subjectFk;
		this.subjectTypeFk = subjectTypeFk;
		this.country = country;
		this.county = county;
		this.townVillage = townVillage;
		this.streetAddress = streetAddress;
		this.zipcode = zipcode;
	}

	public long getAddress() {
		return this.address;
	}

	public void setAddress(long address) {
		this.address = address;
	}

	public Long getAddressTypeFk() {
		return this.addressTypeFk;
	}

	public void setAddressTypeFk(Long addressTypeFk) {
		this.addressTypeFk = addressTypeFk;
	}

	public Long getSubjectFk() {
		return this.subjectFk;
	}

	public void setSubjectFk(Long subjectFk) {
		this.subjectFk = subjectFk;
	}

	public Long getSubjectTypeFk() {
		return this.subjectTypeFk;
	}

	public void setSubjectTypeFk(Long subjectTypeFk) {
		this.subjectTypeFk = subjectTypeFk;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getTownVillage() {
		return this.townVillage;
	}

	public void setTownVillage(String townVillage) {
		this.townVillage = townVillage;
	}

	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

}
