package backend.model.hibernate_reverse;
// default package
// Generated Jun 8, 2012 6:23:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * EmployeeRoleType generated by hbm2java
 */
public class EmployeeRoleType implements java.io.Serializable {

	private long employeeRoleType;
	private String typeName;

	public EmployeeRoleType() {
	}

	public EmployeeRoleType(long employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

	public EmployeeRoleType(long employeeRoleType, String typeName) {
		this.employeeRoleType = employeeRoleType;
		this.typeName = typeName;
	}

	public long getEmployeeRoleType() {
		return this.employeeRoleType;
	}

	public void setEmployeeRoleType(long employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
